{{- if .Values.keyVaultCSI.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.keyVaultCSI.secretProviderClassName }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.secrets.name }}
      type: Opaque
      data:
        {{- range .Values.keyVaultCSI.secretObjects }}
        - objectName: {{ .objectName }}
          key: {{ .key }}
        {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.keyVaultCSI.clientId | quote }}
    keyvaultName: {{ .Values.keyVaultCSI.keyVaultName | quote }}
    tenantId: {{ .Values.keyVaultCSI.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.keyVaultCSI.secretObjects }}
        - |
          objectName: {{ .objectName }}
          objectType: secret
        {{- end }}
{{- end }}
